import type { Metadata } from "next";
import "./globals.css";
import { brfirma, cabinetGrotesk } from "./font";

export const metadata: Metadata = {
  title: "10alytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable} ${brfirma.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
